install.packages("devtools",repos ="https://mirrors.tuna.tsinghua.edu.cn/CRAN/",quietly=TRUE)
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager",repos ="https://mirrors.tuna.tsinghua.edu.cn/CRAN/",quietly=TRUE)
BiocManager::install("S4Vectors")
BiocManager::install("SingleCellExperiment")
BiocManager::install("Seurat")
BiocManager::install("SeuratDisk")
BiocManager::install("scater")
BiocManager::install("Signac")
BiocManager::install("scry")
BiocManager::install("dplyr")
BiocManager::install("patchwork")
BiocManager::install("reticulate")
BiocManager::install("glmGamPoi")
BiocManager::install("kstreet13/slingshot")
BiocManager::install("BiocNeighbors")
BiocManager::install("ComplexHeatmap")
BiocManager::install("limma")
devtools::install_github('satijalab/seurat-data')
devtools::install_github("sqjin/CellChat")
devtools::install_github("saeyslab/nichenetr")
install.packages('Matrix',repos ="https://mirrors.tuna.tsinghua.edu.cn/CRAN/",quietly=TRUE)
install.packages("uwot",repos ="https://mirrors.tuna.tsinghua.edu.cn/CRAN/",quietly=TRUE)
install.packages("mclust",repos ="https://mirrors.tuna.tsinghua.edu.cn/CRAN/",quietly=TRUE)
install.packages("CellChat",repos ="https://mirrors.tuna.tsinghua.edu.cn/CRAN/",quietly=TRUE)
install.packages("tidyverse",repos ="https://mirrors.tuna.tsinghua.edu.cn/CRAN/",quietly=TRUE)
remotes::install_github("mojaveazure/seurat-disk")
